name: Docker Build

on:
  push:
    branches:
    - master
    - release
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker compose
      run: docker-compose up -d
