name: Docker Build

on:
  push:
    branches:
    - master
    - release
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the containers
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: App Logs
      run: docker logs app 

