name: Upload to github pages

on:
  push:
    branches:
      - feature/html-reports

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: build containers
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the containers
      run: docker-compose -f docker-compose-prod.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Build mvn
      run: cd App && DB_HOST=localhost mvn -ntp clean compile assembly:single
    - name: Run jar
      run: cd App && DB_HOST=localhost java -jar ./target/seMethods-1.0-jar-with-dependencies.jar
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./App
